---
title: "Quantitatives methods for the history of economics"
subtitle: "Textual, bibliometric and prosopographical analyses"
author: "Thomas Delcey"
output:
  html_document:
    number_sections: true
    toc: true
    toc_float: true
    code_folding: show
  pdf_document: 
    latex_engine: xelatex
bibliography: bibliography.bib
link-citations: true
---

```{r setup, include = FALSE}
library(knitr)
library(formatR)
opts_chunk$set(warning = FALSE, message = FALSE)
knitr::opts_chunk$set(tidy.opts = list(width.cutoff = 60), tidy = TRUE)
```

```{r include = FALSE}
library(here)
source(here("rmd", "0_paths_and_packages.R"))

reticulate::use_condaenv(condaenv = env_python_path)
#reticulate::conda_install("env_python_path", "gensim")
```

# Becoming an economist

## Introduction

```{r child = here::here("rmd", "introduction.rmd")}
```


## Data  

```{r child = here::here("rmd", "part1_textual_data", "2.corpus", "categorizing.rmd")}
```


d = here::here("rmd", "part1_textual_data", "2.corpus", "regex.rmd")}
```

## Descriptive analysis on french Ph.D.

```{r child = here::here("rmd", "part1_textual_data", "3.representation", "tokenization.rmd")}
```



## An application: internationalization of economics in France 

```{r child = here::here("rmd", "part1_textual_data", "4.measurements", "concepts_detection.rmd")}
```




