```{r include = FALSE, message = FALSE, eval = FALSE}
library(here)
source(here("0_paths_and_packages.R"))
```

```{r include = FALSE, message = FALSE}

thesis_table <- readRDS(here(FR_cleaned_data_path, "thesis_table.rds")) %>% 
  ungroup()

people_table <- readRDS(here(FR_cleaned_data_path, "people_table.rds"))
institution_table <- readRDS(here(FR_cleaned_data_path, "University_table.rds"))

```

## Documents 


### Distribution over time 


```{r}
gg <- thesis_table  %>%
  filter(date < 2020) %>%
  count(date) %>%
  ggplot() +
  geom_line(aes(x = as.numeric(date), y = n), colour = "darkred", 
            linewidth = 1.5) +
  labs(y = "Documents",
       x = "",
       title = "Number of documents in the database") +
  theme_classic()

ggsave("disribution_thesis.jpg", plot = gg, path = here(figures_path, "descriptive_analysis"), width=6, height=4, dpi=300)

print(gg)
```

### Sources of data

```{r}
gg <- thesis_table  %>%
  filter(date < 2020) %>%
  group_by(date, database) %>%
  summarise(n = n()) %>%
  ggplot() +
  geom_line(aes(
    x = as.numeric(date),
    y = n,
    colour = database
  ),
  linewidth = 1.5) +
  scale_color_manual(
    name = "",
    values = c(
      "sudoc" = "darkred",
      "thesefr" = "darkblue",
      "sudoc_law" = "darkgreen"
    ),
    labels = c("Sudoc économie", "Sudoc droit", "These.fr")
  ) +
  labs(
    y = "Documents",
    x = "",
    title = "Number of documents in the database",
    subtitle  = "With sources",
  ) +
  theme_classic() +
  theme(legend.position = "bottom")#'she/he is an economists and did an econ PHD (if less than 5, it could be a law researcher that is doing interdisciplinary research)
ggsave("disribution_thesis_with_sources.jpg", plot = gg, path = here(figures_path, "descriptive_analysis"), width=6, height=4, dpi=300)

print(gg)
```

### The heterogeneity of French PhD before 1984

```{r}
eval_thesis_kind <- thesis_table %>%
  ungroup() %>%
  select(doc_id, thesis_type, date) %>%
  mutate(
    thesis_type2 = case_when(
      str_detect(thesis_type, "3e [Cc]ycle|[Ss]pécialité") ~ "Thèse de troisième cycle",
      str_detect(thesis_type, "ingénieur") ~ "Thèse d'ingénieur",
      TRUE ~ "Thèse de doctorat"
    )
  ) %>%
  count(thesis_type2, date) %>%
  filter(date < 1986) 

gg <- ggplot(
    data = eval_thesis_kind,
    aes(x = as.integer(date),
        y = n,
        color = thesis_type2,
        linetype=thesis_type2, 
        shape=thesis_type2),
  ) +
  geom_line(linewidth = 1.5) + 
  geom_point(size = 1.6,
             fill = "red") +
  scale_linetype_manual(
    name = "",
    values = c(
      "Thèse de troisième cycle" = "solid",
      "Thèse de doctorat" = "solid",
      "Thèse d'ingénieur" = NA
  )) + 
  scale_shape_manual(
    name = "",
    values = c(
      "Thèse de troisième cycle" = NA,
      "Thèse de doctorat" = NA,
      "Thèse d'ingénieur" = 21
  )) +   
  scale_color_manual(
    name = "",
    values = c(
      "Thèse de troisième cycle" = "orange",
      "Thèse de doctorat" = "darkred",
      "Thèse d'ingénieur" = "red"
    )
  ) +
  labs(
    x = "",
    y = "Documents",
    title = "The different french PhD before 1985",
  ) +
  theme_classic() +
  theme(legend.position = "bottom")  

ggsave("disribution_thesis_with_types.jpg", plot = gg, path = here(figures_path, "descriptive_analysis"), width=6, height=4, dpi=300)

print(gg)
```

## Metadata 

### Global data 

```{r}
metadata <- thesis_table %>%
  left_join(people_table %>% 
              filter(role == "supervisor") %>%
              select(doc_id, role)) %>%
  left_join(institution_table, by = "doc_id") %>%
  rename("Date of defense" = date,
         "Language" = language,
         "Author" = first_author,
         "Supervisor" = role,
         "Title in French" = title.fr,
         "Standarized keywords" = topics_standarized,
         "Abstract in French" = abstract.fr,
         "Title in English" = title.en,
         "Abstract in English" = abstract.en) 
  
eval_global <-
  as.data.frame(colSums(!is.na(
    metadata %>%
      select(-doc_id,-database,-thesis_type, -topics_author.fr, -topics_author.en)
  )) / nrow(metadata) * 100) %>%
  rownames_to_column("variables") %>%
  rename("na" = 2)

gg <- eval_global %>%
  mutate(variables = fct_reorder(variables, na)) %>%
  ggplot() +
  geom_col(aes(x = variables,
               y = na,
               fill = na),
           alpha = 0.9, 
           show.legend = FALSE) +
  coord_flip() +
  scale_fill_gradient(
  name = "",
  low = "darkred",
  high = "darkgreen") +
  labs(
    x = "",
    y = "%",
    title = "Availability of metadata",
    subtitle = "in % of total documents"
  ) +
  theme_classic()

ggsave("metadata_evaluation.jpg", plot = gg, path = here(figures_path, "descriptive_analysis"), width=6, height=4, dpi=300)

print(gg)
```

### Textual data 

#### Abstracts 

```{r}
abstract_eval <- thesis_table %>%
  ungroup() %>%
  select(date, doc_id, abstract.fr, abstract.en) %>%
  add_count(date, name = "n_thesis") %>%
  mutate(
    na_ab = case_when(
      is.na(abstract.fr) & is.na(abstract.en) ~ "Not Available",
      is.na(abstract.fr) &
        !is.na(abstract.en) ~ "Only in English",!is.na(abstract.fr) ~ "In French"
    )
  ) %>%
  add_count(date) %>%
  add_count(na_ab, date) %>%
  select(date, na_ab, n, nn) %>%
  mutate(nnn = nn / n * 100) %>%
  unique()

abstract_eval %>%
  ggplot() +
  geom_col(aes(x = as.integer(date), y = nnn, fill = na_ab),
           position = "stack") +
  scale_fill_manual(
    name = "",
    values = c(
      "Not Available" = "darkred",
      "In French" = "darkgreen",
      "Only in English" = "green3"
    )
  ) +
  labs(x = "", y = "%", title = "Summary of data: abstracts") +
  theme_classic() +
  theme(legend.position = "bottom")
``` 

#### Titles 


```{r}
title_eval <- thesis_table %>%
  ungroup() %>%
  select(date, doc_id, title.fr, title.en) %>%
  add_count(date, name = "n_thesis") %>%
  mutate(
    na_title = case_when(
      is.na(title.fr) & is.na(title.en) ~ "Not Available",
      is.na(title.fr) &
        !is.na(title.en) ~ "Only in English",
      !is.na(title.fr) ~ "In French"
    )
  ) %>%
  add_count(date) %>%
  add_count(na_title, date) %>%
  select(date, na_title, n, nn) %>%
  mutate(nnn = nn / n * 100) %>%
  unique()


title_eval %>%
  ggplot() +
  geom_col(aes(x = as.integer(date), 
               y = nnn, 
               fill = na_title),            
           position = "stack") +
  scale_fill_manual(
    name = "",
    values = c(
      "Not Available" = "darkred",
      "In French" = "darkgreen",
      "Only in English" = "green3"
    )
  ) +
  labs(x = "", y = "%", title = "Summary of data: titles") +
  theme_classic() +
  theme(legend.position = "bottom")
```

#### Standarized topics 

```{r}
library(knitr)
library(kableExtra)

thesis_table %>%
  filter(date > 1985) %>%
  sample_n(3) %>%
  select(title.fr, topics_standarized) %>%
  kbl() %>%
  kable_minimal() %>%
  kable_styling(full_width = F,
                latex_options= c("scale_down","HOLD_position"))

```

```{r}
topic_eval <- thesis_table %>%
  mutate(na_topic = ifelse(is.na(topics_standarized), "Not available",
                             "Available")) %>%
  add_count(date) %>%
  add_count(na_topic, date) %>%
  select(date, na_topic, n, nn) %>%
  mutate(nnn = nn / n * 100) %>%
  unique()

  
topic_eval %>%
  ggplot() +
  geom_col(aes(x = as.integer(date), 
                y = nnn, 
                fill = na_topic),
            position = "stack") +
  scale_fill_manual(
    name = "",
    values = c(
      "Not available" = "darkred",
      "Available" = "darkgreen"
    )
  ) +
  labs(
    x = "",
    y = "%",
    title = "Summary of data: topics",
    subtitle = "Classification 'Rameaux'"
  ) +
  theme_classic() +
  theme(legend.position = "bottom")

```
### People 


#### Authors 

```{r}
eval_author <- thesis_table %>%
  left_join(people_table %>%
              filter(role == "author")) %>%
  mutate(na_author = ifelse(is.na(role), "Not available", "Available")) %>% 
  add_count(date) %>%
  add_count(na_author, date) %>%
  select(date, na_author, n, nn) %>%
  mutate(nnn = nn / n * 100) %>%
  unique()

eval_author %>%
  ggplot() +
  geom_col(aes(x = as.integer(date),
               y = nnn,
               fill = na_author),
           position = "stack") +
  scale_fill_manual(
    name = "",
    values = c(
      "Not available" = "darkred",
      "Available" = "darkgreen"
    )
  ) +
  labs(x = "",
       y = "%",
       title = "Summary of data: authors") +
  theme_classic() +
  theme(legend.position = "bottom")
```


#### Supervisor 

```{r}
eval_supervisor <- thesis_table %>%
  ungroup() %>%
  left_join(people_table %>%
              filter(role == "supervisor")) %>%
  mutate(na_sup = ifelse(is.na(role), "Not available", "Available")) %>% 
  add_count(date) %>%
  add_count(na_sup, date) %>%
  select(date, na_sup, n, nn) %>%
  mutate(nnn = nn / n * 100) %>%
  unique()

eval_supervisor %>%
  ggplot() +
  geom_col(aes(x = as.integer(date),
                y = nnn,
                fill = na_sup),
            position = "stack") +
  scale_fill_manual(
    name = "",
    values = c(
      "Not available" = "darkred",
      "Available" = "darkgreen"
    )
  ) +
  xlim(c(1920, 2022)) +
  labs(x = "",
       y = "%",
       title = "Summary of data: supervisor") +
  theme_classic() +
  theme(legend.position = "bottom") 

```

#### Jury 

```{r}
complete_data <- people_table %>%
  left_join(select(thesis_table, doc_id, date)) %>%
  mutate(role = ifelse(role == "referee", "member", role)) %>%
  mutate(name = paste(prenom, nom)) %>%
  complete(doc_id, role)

check_if_complete <- complete_data %>%
  group_by(doc_id, date) %>%
  summarise(
    author = sum(role == "author" & !is.na(nom)),
    member = sum(role == "member" & !is.na(nom)),
    supervisor = sum(role == "supervisor" & !is.na(nom))
  )

complete <- check_if_complete %>%
  group_by(doc_id, date) %>%
  filter(author > 0 & member > 0 & supervisor > 0) %>%
  count() %>%
  filter(!is.na(date))


incomplete <- check_if_complete %>%
  group_by(doc_id, date) %>%
  filter(!(author > 0 & member > 0 & supervisor > 0)) %>%
  count() %>%
  filter(!is.na(date))

# total <- nrow(complete) + nrow(incomplete)

gg <- ggplot() +
  geom_bar(
    data = complete,
    aes(x = "Complete data", y = n),
    stat = "identity",
    fill = "darkgreen"
  ) +
  geom_bar(
    data = incomplete,
    aes(x = "Incomplete data", y = n),
    stat = "identity",
    fill = "darkred"
  ) +
  labs(x = "", 
       y = "Number of documents", 
       title = "Availability of jury data") +
  theme_classic()

ggsave("jury_evaluation.jpg", plot = gg, path = here(figures_path, "descriptive_analysis"), width=6, height=4, dpi=300)

print(gg)
```


```{r}
complete_data <- people_table %>%
  left_join(select(thesis_table, doc_id, date)) %>%
  mutate(role = ifelse(role == "referee", "member", role)) %>%
  mutate(name = paste(prenom, nom)) %>%
  complete(doc_id, role)

check_if_complete <- complete_data %>%
  group_by(doc_id, date) %>%
  summarise(
    author = sum(role == "author" & !is.na(nom)),
    member = sum(role == "member" & !is.na(nom)),
    supervisor = sum(role == "supervisor" & !is.na(nom))
  )

complete <- check_if_complete %>%
  group_by(doc_id, date) %>%
  filter(author > 0 & member > 0 & supervisor > 0) %>%
  ungroup() %>%
  count(date) %>%
  filter(!is.na(date)) %>%
  mutate(data = "Complete")


incomplete <- check_if_complete %>%
  group_by(doc_id, date) %>%
  filter(!(author > 0 & member > 0 & supervisor > 0)) %>%
  ungroup() %>%
  count(date) %>%
  filter(!is.na(date)) %>%
  mutate(data = "Incomplete")

eval_jury <- rbind(incomplete, complete) %>%
  group_by(date) %>%
  mutate(total = sum(n)) %>%
  group_by(data) %>%
  mutate(n_perc = n/total*100) %>%
  group_by(date) %>%
  mutate(control = sum(n_perc))

gg <- eval_jury %>% 
  ggplot() +
  geom_col(aes(x = as.integer(date),
               y = n_perc,
               fill = data),
           position = "stack") +
  scale_fill_manual(
    name = "",
    values = c(
      "Incomplete" = "darkred",
      "Complete" = "darkgreen")
  ) +
  labs(x = "", 
       y = "%", 
       title = "Summary of data: jury") +
  theme_classic() +
  
  theme(legend.position = "bottom")

ggsave("jury_evaluation_by_year.jpg", plot = gg, path = here(figures_path, "descriptive_analysis"), width=6, height=4, dpi=300)

print(gg)

```

#### Gender

##### Authors gender 


```{r}
#plot
people_table <- readRDS(here(FR_cleaned_data_path, "people_table.RDS")) %>% as.data.table()

author_gender <- people_table[role=="author"]

hist_author_gender <- author_gender[,.N,.(gender_cleaned,date)]
hist_author_gender[,tot:=sum(N),date]
hist_author_gender[,share:=N/tot*100]

gg <- ggplot(data=hist_author_gender[date>=1950], aes(x=as.numeric(date), y=share, fill=gender_cleaned)) +
  geom_bar(stat="identity", alpha = 0.7)+
  scale_fill_brewer(name = "Genre",
                    palette="Dark2")+
  theme_light() +
  labs(x = "",
       y = "%",
       title = "Gender of authors")

ggsave("gender_authors.jpg", plot = gg, path = here(figures_path, "descriptive_analysis"), width=6, height=4, dpi=300)

print(gg)
```


##### Supervisor gender 

```{r}
supervisor_gender <- people_table[role=="supervisor"]
hist_supervisor_gender <- supervisor_gender[,.N,.(gender_cleaned,date)]
hist_supervisor_gender[,tot:=sum(N),date]
hist_supervisor_gender[,share:=N/tot*100]

gg <- ggplot(data=hist_supervisor_gender[date>=1950], aes(x=as.numeric(date), y=share, fill=gender_cleaned)) +
  geom_bar(stat="identity", alpha = 0.7)+
  scale_fill_brewer(name = "Genre",
                    palette="Dark2")+
  theme_light() +
  labs(x = "",
       y = "%",
       title = "Gender of supervisors")

ggsave("gender_supervisors.jpg", plot = gg, path = here(figures_path, "descriptive_analysis"), width=6, height=4, dpi=300)

print(gg)

```





