```{r include = FALSE, message = FALSE, eval = FALSE}
library(here)
source(here("0_paths_and_packages.R"))
```

```{r include = FALSE, message = FALSE}

thesis_table <- readRDS(here(FR_cleaned_data_path, "thesis_table.rds")) %>% 
  ungroup()

people_table <- readRDS(here(FR_cleaned_data_path, "people_table.rds"))
```


## Language of PhD 

```{r}
distribution_languages  <-
  thesis_table  %>%
  filter(str_detect(language, "^fr$|^en")) %>%
  filter(date %in% c(1990:2020)) %>%
  count(language, date) %>%
  group_by(date) %>%
  mutate(n_perc = n / sum(n) * 100) %>%
  mutate(language = case_when(language == "fr" ~ "French",
                              language == "en" ~ "English",
                              language == "enfr" ~ "Both"))

distribution_languages %>%
  ggplot() +
  geom_line(aes(
    x = as.numeric(date),
    y = n_perc,
    colour = language
  ),
  linewidth = 1.5) +
  scale_color_manual(
    name = "Langue de la thèse",
    values = c(
      "French" = "darkred",
      "English" = "darkblue",
      "Both" = "darkgreen"
    )
  ) +
  ylab("Proportion") +
  xlab("") +
  theme_light() 



```


## Standarization of PhD format 


```{r, message = FALSE}
format_thesis <- thesis_table %>%
  select(title.fr, date) %>%
  group_by(date) %>%
  unnest_tokens(input = title.fr,
               output = token) %>%
  add_count(date) %>%
  filter(str_detect(token, "essais")) %>%
  add_count(date)

format_thesis %>%
  ggplot() +
  geom_line(aes(x = as.numeric(date), y = nn/n), 
            linewidth = 1.5,
            colour = "darkblue") +
  labs(
    x = "",
    y = "Normalized term frequency",
    title = "The PhD standarization",
    subtitle = "PhD mentionning 'essays' in their titles",
    caption = "Note: Frequency normalized by the size of the corpus"
  ) + 
  theme_light()
```
```{r}
thesis_table %>%
  select(title.fr, date) %>%
  filter(str_detect(title.fr, "essais")) %>%
  add_count(date) %>%
  ggplot() +
  geom_smooth(aes(x = as.numeric(date), y = n), 
            method = "loess",
            se = F,
            linewidth = 1.5,
            colour = "darkblue") + 
  labs(
    x = "",
    y = "Documents",
    title = "The PhD standarization",
    subtitle = "Number of thesis mentionning 'essais' in the title",
    caption = "Note: Frequency normalized by the size of the corpus"
  ) + 
  theme_light() +
  ggplot2::annotate("text", 
                    x=max(as.numeric(thesis_table$date)), 
                    y=-Inf, 
                    hjust=.95,
                    vjust=-0.5,
                    label="Curves smoothed by local polynomial regression",
                    size=3, 
                    color="darkgrey")

```





